package Chapter1_VariablesAndDataType;

//Java is a high-level, object-oriented, platform-independent programming language.

//Java follows this:
//Java Code
//      ↓
//Compiler
//      ↓
//Bytecode (.class)
//      ↓
//JVM
//      ↓
//Machine Code

//Isliye Java ka famous slogan hai:
//Write Once, Run Anywhere (WORA)
//Ek hi .class file Windows, Linux aur macOS par chal sakti hai, bas us system me JVM installed honi chahiye.

/*
JDK
├── Compiler (javac)
├── JRE
│      ├── JVM
│      └── Libraries
└── Development Tools

Java
A high-level, object-oriented, platform-independent programming language that follows the principle Write Once, Run Anywhere (WORA).

Source Code
The human-readable Java code written by the programmer and stored in a .java file.

Compiler
A tool (javac) that checks Java source code for errors and converts it into bytecode.

Compilation
The process of converting Java source code (.java) into bytecode (.class).

Bytecode
An intermediate, platform-independent code generated by the Java compiler, stored in a .class file, and executed by the JVM.

JVM
The Java Virtual Machine. It loads and executes bytecode by converting it into machine code for the underlying operating system.

JRE
The Java Runtime Environment. It provides everything needed to run Java programs, including the JVM and standard libraries.

JDK
The Java Development Kit. It provides everything needed to develop and run Java programs, including the compiler (javac), JRE, JVM, and development tools.
 */

public class Hello_world {
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}

//public -> access modifiers
//class -> blueprint/template
//Hello_world -> file name and class name
//static -> method ke object banane nhi padte automatic chal jata hai
//void -> means the function returning nothing
//main -> method name or main function
//String[] args -> advanced topic